---
# handlers file for apache
- name: Run debian apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Restart debian apache
  service:
    name: apache2
    state: reloaded

- name: Run CentOs apache
  service:
    name: httpd
    state: started
    enabled: yes