---
# tasks file for nginx


- name: Install Nginx
  apt:
    name=nginx state=present update_cache=yes
  when:
    ansible_os_family == "Debian"
  notify:
    - Nginx Systemd

- name: Delete default HTML files
  shell: /bin/rm -rf /usr/share/nginx/html/*.html
  args:
    warn: false

- name: Replace config file
  vars:
    nginx_user: user
    worker_processes: 2
    worker_connections: 256
    worked_by: "Proxypepe"
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  register: result
  failed_when: result.failed == true
  notify: Reload Nginx

- name: Copy index file
  copy: src=index.html dest={{ html_dir }} mode=0644
  notify: Reload Nginx

- name: Generate dynamic HTML from template
  template:
    src=hello.html.j2 dest={{ html_dir }}/hello.html owner=root mode=0644
  notify: Reload Nginx
