---
- hosts: all

  become: yes

  tasks:
    - name: Install Apache.
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - apache2
        - apache2-dev 
    - name: Copy configutation files.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: "apache2.conf"
          dest: "/ect/apache2/"
    - name: Make sure Apache is started now and at boot
      service: name=apache2 state=started enabled=yes