---
- hosts: ubuntu

  vars_files:
    - vars.yml

  tasks:
    - name: Install Docker python.
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - python3-docker

    - name: create build directory
      file:
        path: /test
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: copy Dockerfile
      copy:
        src: ./test/Dockerfile
        dest: /test
        owner: root
        group: root
        mode: '0644'

    - name: build container image
      docker_image:
        name: democontainer:v1.0
        build:
          path: /test
        source: build
        state: present

    - name: Run the test container.
      docker_container:
        name: democontainer
        image: democontainer:v1.0
        state: started

