---
# tasks file for bitbucket-update

- name: Download | Download archive
  ansible.builtin.get_url:
    url: "{{ bitbucket_url }}/{{ bitbucket_package }}.tar.gz"
    dest: "/tmp/{{ bitbucket_package }}.tar.gz"
  register: download_bitbucket
  tags: bitbucket_install

- name: Download | Extract archive
  ansible.builtin.unarchive:
    src: "/tmp/{{ bitbucket_package }}.tar.gz"
    dest: "{{ bitbucket_install_dir }}"
    copy: false
    mode: 'u=rwx,g=rx,o=rx'
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_user }}"
  tags: bitbucket_install

- name: Configure | Copy all bin config templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ bitbucket_install_dir }}/atlassian-bitbucket-{{ bitbucket_version }}/bin/{{ item | basename | splitext | first }}"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: 'u=rwx,g=rwx,o=rwx'
  with_fileglob:
    - templates/bin/*
  tags: bitbucket_configure

- name: Configure | Copy Bitbucket properties
  ansible.builtin.template:
    src: "{{ bitbucket_properties_template_path }}"
    dest: "{{ bitbucket_home_dir }}/shared/bitbucket.properties"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    mode: 'u=rwx,g=rwx,o=rwx'
  tags: bitbucket_configure

- name: Configure | Create a symbolic link
  ansible.builtin.file:
    src: "{{ bitbucket_install_dir }}/atlassian-bitbucket-{{ bitbucket_version }}"
    dest: "{{ bitbucket_install_dir }}/curr"
    owner: "{{ bitbucket_user }}"
    group: "{{ bitbucket_group }}"
    state: link

- name: Service | Start unit service
  ansible.builtin.command:
    cmd: sudo /bin/systemctl restart bitbucket
  changed_when: false
  tags: bitbucket_service
